using MediatR;
using System.Threading;
using System.Threading.Tasks;

public class CreateDepartmentCommandHandler : IRequestHandler<CreateDepartmentCommand, Department>
{
    private readonly IDepartmentService _departmentService;

    public CreateDepartmentCommandHandler(IDepartmentService departmentService)
    {
        _departmentService = departmentService;
    }

    public async Task<Department> Handle(CreateDepartmentCommand request, CancellationToken cancellationToken)
    {
        // Business logic for creating a department
        var departmentsList = (await _departmentService.GetDepartmentsAsync()).ToList();

        var newDepartment = new Department
        {
            Id = departmentsList.Count + 1, // Just a simple way to generate an ID (in a real scenario, it would be generated by the database)
            Name = request.Name
        };

        // Add department to service (you'd typically save this to a database)
        // For simplicity, we add it to an in-memory list.
        departmentsList.Add(newDepartment);

        return newDepartment; // Return the newly created department
    }
}
